band_width_factor: 1.6
stop_loss_percentage: 0.30
median_periods: 6
risk_ratio: 0.9

trading_instrument: "EURUSD"

# "UBSG.SW""SREN.SW""UBSG.SW" "ABBN.SW" 'ALC.SW' 'GEBN.SW' 'GIVN.SW' 'HOLN.SW' 'KNIN.SW' 'LOGN.SW' 'LONN.SW' 'NESN.SW' 'NOVN.SW': 'Novartis'
# 'PGHN.SW' 'CFR.SW' 'ROG.SW' 'SIKA.SW' 'SOON.SW' 'SLHN.SW' 'SCMN.SW' 'UBSG.SW' 'ZURN.SW': 'ZurichInsurance'

# median periods for calculations on historical data
median_data_60min: 6
median_data_1440min: 6
median_data_10080min: 6
